# Generated by Django 4.2.7 on 2023-12-04 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='form',
            old_name='lname',
            new_name='cpassword',
        ),
        migrations.RenameField(
            model_name='form',
            old_name='mname',
            new_name='username',
        ),
    ]
